on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy with Maven
      env:
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        GH_PASSWORD: ${{ secrets.GH_PASSWORD }}
      run: mvn -B deploy --settings ./settings.xml
