on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 8

    - name: Build and Deploy with Maven
      env:
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        GH_PASSWORD: ${{ secrets.GH_PASSWORD }}
      run: mvn -B deploy --settings ./settings.xml
